#!/usr/bin/env node
// Generates TypeScript types (ts/generated/*.ts) and Python pydantic models
// (services/backend/studymate/protocol/*.py) from schema/*.schema.json.
// The schemas are the single source; never edit generated files by hand.
import { compile } from 'json-schema-to-typescript';
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const repo = resolve(root, '../..');
const schemaDir = join(root, 'schema');
const tsOut = join(root, 'ts/generated');
const pyOut = join(repo, 'services/backend/studymate/protocol');
const BANNER = '// GENERATED by packages/protocol/scripts/gen.mjs from schema/*.schema.json. Do not edit.\n';

/** Message unions whose member `type` constants are exported as runtime sets. */
const UNIONS = ['GodotCommand', 'GodotEvent', 'ClientMessage', 'ServerMessage'];

mkdirSync(tsOut, { recursive: true });
mkdirSync(pyOut, { recursive: true });

const modules = [];
for (const file of readdirSync(schemaDir).filter((f) => f.endsWith('.schema.json'))) {
  const name = file.replace('.schema.json', '');
  const schema = JSON.parse(readFileSync(join(schemaDir, file), 'utf-8'));
  modules.push(name);

  // Expose every $def as a named type by referencing it from a synthetic root.
  const rootSchema = {
    $defs: schema.$defs,
    title: `${name}Root`,
    type: 'object',
    additionalProperties: false,
    properties: Object.fromEntries(
      Object.keys(schema.$defs).map((k) => [k, { $ref: `#/$defs/${k}` }]),
    ),
  };
  let ts = await compile(rootSchema, `${name}Root`, {
    bannerComment: BANNER,
    additionalProperties: false,
    strictIndexSignatures: true,
    ignoreMinAndMaxItems: true,
    format: true,
    style: { singleQuote: true, printWidth: 100 },
  });
  // The synthetic root is only a vehicle; drop it.
  ts = ts.replace(new RegExp(`export interface ${name}Root \\{[\\s\\S]*?\\n\\}\\n`), '');

  for (const union of UNIONS) {
    const def = schema.$defs[union];
    if (!def) continue;
    const types = def.oneOf.map((m) => {
      const target = schema.$defs[m.$ref.split('/').pop()];
      return target.properties.type.const;
    });
    ts += `\nexport const ${constName(union)} = new Set<${union}['type']>(${JSON.stringify(types)});\n`;
  }
  writeFileSync(join(tsOut, `${name}.ts`), ts);

  // Python: pydantic v2 models via datamodel-code-generator (dev dependency of the backend).
  const py = spawnSync(
    'uv',
    [
      'run', '--project', join(repo, 'services/backend'), 'datamodel-codegen',
      '--input', join(schemaDir, file),
      '--input-file-type', 'jsonschema',
      '--output', join(pyOut, `${name}.py`),
      '--output-model-type', 'pydantic_v2.BaseModel',
      '--target-python-version', '3.11',
      '--use-annotated',
      '--collapse-root-models',
      '--formatters', 'black', 'isort',
      '--use-union-operator',
      '--use-standard-collections',
      '--use-title-as-name',
      '--enum-field-as-literal', 'all',
      '--disable-timestamp',
      '--custom-file-header', '# GENERATED by packages/protocol/scripts/gen.mjs. Do not edit.',
    ],
    { stdio: 'inherit' },
  );
  if (py.status !== 0) {
    console.error(`[gen] datamodel-codegen failed for ${file}`);
    process.exit(1);
  }
  console.log(`[gen] ${name}: ts + py`);
}

writeFileSync(join(tsOut, 'index.ts'), BANNER + modules.map((m) => `export * from './${m}';\n`).join(''));
writeFileSync(join(pyOut, '__init__.py'), '# GENERATED package marker.\n');

function constName(union) {
  return union.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase() + '_TYPES';
}
