# GENERATED by packages/protocol/scripts/gen.mjs. Do not edit.

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class DirectorUIBackendMessages(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description='Transport: WebSocket ws://127.0.0.1:8765/ws. Every message is {type, id?, ...}; responses reuse the request id.',
            title='Director/UI <-> Backend messages',
        ),
    ]


class Mark(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['circle', 'underline', 'arrow']
    target: Annotated[
        str, Field(description='LaTeX fragment of the written line to mark')
    ]


class ScriptStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    say: Annotated[str, Field(description='Korean narration for TTS')]
    write: Annotated[
        str | None,
        Field(description='LaTeX to hand-write; plain sentences wrapped in \\text{}'),
    ] = None
    mark: Mark | None = None
    gesture: Literal['write', 'point', 'nod', 'tap_desk', 'throw', 'idle'] | None = None
    emotion: Literal['happy', 'surprised', 'sleepy', 'angry', 'neutral'] | None = None
    role: Annotated[
        Literal['intro', 'concept', 'solve', 'check', 'summary'] | None,
        Field(
            description="Teaching role of a step: intro = what the problem asks, concept = the unit's key idea, solve = a line of working, check = substitution check, summary = one-line takeaway"
        ),
    ] = None
    note: Annotated[
        str | None,
        Field(
            description='Short margin note written beside the line (e.g. "-5 이항", "양변 ÷ 2")',
            max_length=24,
        ),
    ] = None


class SolveScript(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    problem_latex: str
    final_answer: str
    verified: bool
    confidence: Literal['high', 'medium', 'low']
    steps: Annotated[list[ScriptStep], Field(min_length=1)]
    unit: Annotated[
        str | None, Field(description='Curriculum unit, e.g. "중1 · 일차방정식"')
    ] = None
    subject: Annotated[
        Literal[
            'math', 'korean', 'english', 'korean_history', 'social', 'science', 'other'
        ]
        | None,
        Field(
            description='Subject of the unit; non-math lessons are evidence-style (the check step is a confirmation, not a calculation)'
        ),
    ] = None
    problem_id: Annotated[
        str | None,
        Field(
            description='The backend keeps the full problem text in memory under this id (last 20 problems, never on disk); follow-up questions pass it back as ask_request.problem_id'
        ),
    ] = None


class QuizSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc_id: str
    page: int
    excerpt: str | None = None


class Solution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    steps: list[ScriptStep]


class DocInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc_id: str
    title: str
    pages: Annotated[
        int, Field(description='Page count; page numbers elsewhere are 1-based')
    ]
    chunks: int
    imported_at: str
    empty_pages: Annotated[
        list[int] | None,
        Field(
            description='1-based pages without a text layer (scanned) that were skipped'
        ),
    ] = None


class PhonemeTiming(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    char: Annotated[
        str,
        Field(
            description='Spoken unit: Hangul syllable (ko), kana mora (ja) or word/phoneme group (en)'
        ),
    ]
    start_ms: float
    end_ms: float
    vowel: Annotated[
        Literal['a', 'i', 'u', 'e', 'o', 'n'] | None,
        Field(
            description="Mouth shape of the unit's vowel (n = closed: m/b/p or silence); language-independent lip-sync input. Derived from char for ko when omitted"
        ),
    ] = None


class GpuInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    vram_gb: float


class HardwareInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cpu: str
    cores: int
    ram_gb: float
    gpus: list[GpuInfo]
    recommended_tier: Literal['lite', 'standard', 'pro', 'max']
    reason: str


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    solve: bool
    vision: bool
    tts: bool
    stt: bool
    drowsy: bool
    rag: bool


class ChatTurn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Literal['user', 'assistant']
    text: str


class SetGpuUse(BaseModel):
    type: Literal['set_gpu_use']
    id: str | None = None
    gpu_use: Annotated[
        Literal['high', 'balanced', 'low'],
        Field(
            description='How much of the AI work runs on the GPU: high = all of it (fastest); balanced = part of the language model on the CPU; low = the language model on the CPU (slowest, no reasoning pass). Embeddings always run on the CPU; the vision model stays on the GPU'
        ),
    ]


class SetTier(BaseModel):
    type: Literal['set_tier']
    id: str | None = None
    tier: Literal['lite', 'standard', 'pro', 'max']


class DownloadModel(BaseModel):
    type: Literal['download_model']
    id: str
    model_id: str


class DownloadProgress(BaseModel):
    type: Literal['download_progress']
    id: str
    model_id: str
    file: str
    downloaded: int
    total: int | None = None
    done: bool


class SolveRequest(BaseModel):
    type: Literal['solve_request']
    id: str
    image_base64: Annotated[
        str | None, Field(description='PNG, already cropped to the problem region')
    ] = None
    problem_text: Annotated[
        str | None,
        Field(description='Alternative to image_base64 (typed input, evaluation)'),
    ] = None
    subject_hint: str | None = None


class SolveProgress(BaseModel):
    type: Literal['solve_progress']
    id: str
    stage: Literal['ocr', 'solving', 'verifying', 'retry', 'voicing']
    attempt: int | None = None
    detail: str | None = None


class SolveScriptMessage(BaseModel):
    type: Literal['solve_script']
    id: str
    script: SolveScript


class AskRequest(BaseModel):
    type: Literal['ask_request']
    id: str
    text: Annotated[
        str,
        Field(description="The user's question or remark (typed or from stt_final)"),
    ]
    context: Annotated[
        str | None, Field(description='Optional current problem or topic')
    ] = None
    problem_id: Annotated[
        str | None,
        Field(
            description='solve_script.script.problem_id of the problem the question is about: the backend answers from the full problem text, and a correction ("the answer is ③") is re-solved instead of argued'
        ),
    ] = None
    history: Annotated[
        list[ChatTurn] | None,
        Field(
            description='Previous turns of this conversation, oldest first (shell keeps the conversation)',
            max_length=20,
        ),
    ] = None
    mode: Annotated[
        Literal['question', 'chat'] | None,
        Field(
            description='question = study question (may write on the board); chat = casual conversation (short spoken reply)'
        ),
    ] = None


class AskAnswer(BaseModel):
    type: Literal['ask_answer']
    id: str
    steps: list[ScriptStep]


class TtsAudio(BaseModel):
    type: Literal['tts_audio']
    id: str
    wav_base64: str
    sample_rate: int
    duration_ms: float
    phonemes: list[PhonemeTiming] | None = None


class VoicePresetsGet(BaseModel):
    type: Literal['voice_presets_get']
    id: str | None = None


class VoicePresetDelete(BaseModel):
    type: Literal['voice_preset_delete']
    id: str | None = None
    preset_id: str


class SttStart(BaseModel):
    type: Literal['stt_start']
    id: str


class SttStop(BaseModel):
    type: Literal['stt_stop']
    id: str


class SttLevel(BaseModel):
    type: Literal['stt_level']
    id: str
    level: Annotated[float, Field(ge=0.0, le=1.0)]


class SttPartial(BaseModel):
    type: Literal['stt_partial']
    id: str | None = None
    text: str


class SttFinal(BaseModel):
    type: Literal['stt_final']
    id: str | None = None
    text: str


class GenerateQuiz(BaseModel):
    type: Literal['generate_quiz']
    id: str
    subject: str
    unit: str | None = None
    difficulty: Literal['easy', 'normal', 'hard']
    count: Annotated[int, Field(ge=1, le=20)]
    source_doc_id: str | None = None


class QuizProgress(BaseModel):
    type: Literal['quiz_progress']
    id: str
    done: int
    total: int


class QuizAnswer(BaseModel):
    type: Literal['quiz_answer']
    id: str
    item_id: str
    answer: str


class QuizGraded(BaseModel):
    type: Literal['quiz_graded']
    id: str
    item_id: str
    correct: bool
    correct_answer: Annotated[
        str, Field(description='For multiple choice: the exact choice string')
    ]
    note_id: Annotated[
        str | None,
        Field(description='Set when a wrong answer was saved to the notebook'),
    ] = None


class WrongNotesGet(BaseModel):
    type: Literal['wrong_notes_get']
    id: str | None = None


class WrongNoteDelete(BaseModel):
    type: Literal['wrong_note_delete']
    id: str | None = None
    note_id: str


class ReviewDueGet(BaseModel):
    type: Literal['review_due_get']
    id: str | None = None


class ReviewGrade(BaseModel):
    type: Literal['review_grade']
    id: str
    card_id: str
    rating: Annotated[
        Literal[1, 2, 3, 4], Field(description='FSRS: 1 again, 2 hard, 3 good, 4 easy')
    ]


class ReviewGraded(BaseModel):
    type: Literal['review_graded']
    id: str
    card_id: str
    next_due: str


class DocImport(BaseModel):
    type: Literal['doc_import']
    id: str
    path: Annotated[str, Field(description='Absolute path of a PDF chosen by the user')]


class DocProgress(BaseModel):
    type: Literal['doc_progress']
    id: str
    stage: Literal['extract', 'embed']
    done: int
    total: int


class DocImported(BaseModel):
    type: Literal['doc_imported']
    id: str
    doc: DocInfo


class DocsGet(BaseModel):
    type: Literal['docs_get']
    id: str | None = None


class Docs(BaseModel):
    type: Literal['docs']
    id: str | None = None
    docs: list[DocInfo]


class DocDelete(BaseModel):
    type: Literal['doc_delete']
    id: str | None = None
    doc_id: str


class DrowsyStart(BaseModel):
    type: Literal['drowsy_start']
    id: str | None = None
    sensitivity: Literal['low', 'normal', 'high']
    camera_index: Annotated[int | None, Field(ge=0)] = None


class DrowsyStop(BaseModel):
    type: Literal['drowsy_stop']
    id: str | None = None


class DrowsyCalibration(BaseModel):
    type: Literal['drowsy_calibration']
    progress: Annotated[float, Field(ge=0.0, le=1.0)]
    done: bool
    baseline_ear: float | None = None


class DrowsyStateMessage(BaseModel):
    type: Literal['drowsy_state']
    state: Literal['normal', 'candidate', 'drowsy', 'no_face', 'paused']
    perclos: float
    pitch: Annotated[
        float, Field(description='Head pitch in degrees, positive = looking down')
    ]
    ear: float | None = None


class CameraState(BaseModel):
    type: Literal['camera_state']
    active: bool


class UserActivity(BaseModel):
    type: Literal['user_activity']
    last_input_ms: Annotated[
        float, Field(description='Milliseconds since the last keyboard/mouse/pen input')
    ]


class Error(BaseModel):
    type: Literal['error']
    id: str | None = None
    code: str
    message: Annotated[str, Field(description='User-facing Korean message')]


class SetLanguage(BaseModel):
    type: Literal['set_language']
    id: str | None = None
    lang: Annotated[
        Literal['ko', 'ja', 'en'],
        Field(
            description="App language: UI, the character's speech (LLM output, TTS), speech recognition and curriculum"
        ),
    ]


class UserProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: Annotated[
        str | None,
        Field(
            description="How the character addresses the user (e.g. a name, 선배, マスター). Empty = the character's default. Screened by the backend (length, characters, safety)",
            max_length=20,
        ),
    ] = None


class SetProfile(BaseModel):
    type: Literal['set_profile']
    id: str | None = None
    profile: UserProfile


class QuizItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    item_id: str
    subject: str
    unit: str | None = None
    difficulty: Literal['easy', 'normal', 'hard']
    question_latex: str
    choices: list[str] | None = None
    answer: str
    solution: Solution
    confidence: Literal['high', 'medium', 'low']
    source: QuizSource | None = None


class WrongNote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    note_id: str
    item: QuizItem
    user_answer: str
    created_at: Annotated[str, Field(description='ISO 8601')]
    card_id: str


class ReviewCard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    card_id: str
    item: QuizItem
    due: Annotated[str, Field(description='ISO 8601')]
    state: Literal['learning', 'review', 'relearning']
    reps: int
    lapses: int


class VoicePreset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    preset_id: str
    name: str
    gender: Literal['female', 'male', 'neutral']
    builtin: bool
    pitch_semitones: Annotated[float, Field(ge=-12.0, le=12.0)]
    formant_ratio: Annotated[
        float,
        Field(
            description='Spectral envelope scale; <1 deeper, >1 brighter/younger',
            ge=0.7,
            le=1.4,
        ),
    ]
    speed: Annotated[float, Field(ge=0.5, le=2.0)]
    brightness_db: Annotated[
        float, Field(description='High-shelf gain above 3 kHz', ge=-12.0, le=12.0)
    ]
    warmth_db: Annotated[
        float, Field(description='Low-shelf gain below 250 Hz', ge=-12.0, le=12.0)
    ]
    reverb: Annotated[float, Field(ge=0.0, le=1.0)]
    volume_db: Annotated[float, Field(ge=-24.0, le=12.0)]
    lang: Annotated[
        Literal['ko', 'ja', 'en'] | None,
        Field(description='Language this voice speaks; ko when omitted'),
    ] = None
    speaker: Annotated[
        str | None,
        Field(
            description="Base TTS voice the post-processing applies to; the language's default speaker when omitted"
        ),
    ] = None


class ModelInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model_id: str
    title: str
    category: Literal['runtime', 'llm', 'vision', 'embed', 'stt', 'tts', 'face', 'ocr']
    tiers: list[Literal['lite', 'standard', 'pro', 'max']]
    size: int
    installed: bool
    required: Annotated[
        bool,
        Field(
            description='Needed for the app to work; with `langs`, needed only by users of those languages'
        ),
    ]
    langs: Annotated[
        list[Literal['ko', 'ja', 'en']] | None,
        Field(
            description='Languages that use this model (e.g. a TTS voice); absent = every language. The shell offers and downloads a model only when the current language is listed'
        ),
    ] = None
    license: str
    license_url: str


class Hello(BaseModel):
    type: Literal['hello']
    id: str | None = None
    client: str | None = None
    lang: Annotated[
        Literal['ko', 'ja', 'en'] | None,
        Field(description='Language the shell is set to; backend switches to it'),
    ] = None
    profile: Annotated[
        UserProfile | None,
        Field(description='User profile the shell has saved; backend applies it'),
    ] = None


class Status(BaseModel):
    type: Literal['status']
    id: str | None = None
    version: str
    tier: Literal['lite', 'standard', 'pro', 'max']
    hardware: HardwareInfo
    models: list[ModelInfo]
    capabilities: Capabilities
    lang: Annotated[
        Literal['ko', 'ja', 'en'],
        Field(
            description="App language: UI, the character's speech (LLM output, TTS), speech recognition and curriculum"
        ),
    ]
    profile: Annotated[
        UserProfile | None,
        Field(description='Profile in effect (address after screening)'),
    ] = None
    gpu_use: Annotated[
        Literal['high', 'balanced', 'low'] | None,
        Field(
            description='How much of the AI work runs on the GPU: high = all of it (fastest); balanced = part of the language model on the CPU; low = the language model on the CPU (slowest, no reasoning pass). Embeddings always run on the CPU; the vision model stays on the GPU'
        ),
    ] = None


class TtsRequest(BaseModel):
    type: Literal['tts_request']
    id: str
    text: str
    voice: Annotated[
        str | None, Field(description='preset_id; default preset when omitted')
    ] = None
    preset: Annotated[
        VoicePreset | None, Field(description='Unsaved preset for previewing edits')
    ] = None


class VoicePresets(BaseModel):
    type: Literal['voice_presets']
    id: str | None = None
    presets: list[VoicePreset]
    default_preset_id: str


class VoicePresetSave(BaseModel):
    type: Literal['voice_preset_save']
    id: str | None = None
    preset: VoicePreset
    make_default: bool | None = None


class QuizItems(BaseModel):
    type: Literal['quiz_items']
    id: str
    items: list[QuizItem]


class WrongNotes(BaseModel):
    type: Literal['wrong_notes']
    id: str | None = None
    notes: list[WrongNote]


class ReviewDue(BaseModel):
    type: Literal['review_due']
    id: str | None = None
    cards: list[ReviewCard]
    next_due: Annotated[
        str | None, Field(description='ISO 8601 of the earliest future card, if any')
    ] = None


class ClientMessage(
    RootModel[
        Hello
        | SetTier
        | SetLanguage
        | SetProfile
        | SetGpuUse
        | DownloadModel
        | SolveRequest
        | AskRequest
        | TtsRequest
        | VoicePresetsGet
        | VoicePresetSave
        | VoicePresetDelete
        | SttStart
        | SttStop
        | GenerateQuiz
        | QuizAnswer
        | WrongNotesGet
        | WrongNoteDelete
        | ReviewDueGet
        | ReviewGrade
        | DocImport
        | DocsGet
        | DocDelete
        | DrowsyStart
        | DrowsyStop
        | UserActivity
    ]
):
    root: (
        Hello
        | SetTier
        | SetLanguage
        | SetProfile
        | SetGpuUse
        | DownloadModel
        | SolveRequest
        | AskRequest
        | TtsRequest
        | VoicePresetsGet
        | VoicePresetSave
        | VoicePresetDelete
        | SttStart
        | SttStop
        | GenerateQuiz
        | QuizAnswer
        | WrongNotesGet
        | WrongNoteDelete
        | ReviewDueGet
        | ReviewGrade
        | DocImport
        | DocsGet
        | DocDelete
        | DrowsyStart
        | DrowsyStop
        | UserActivity
    )


class ServerMessage(
    RootModel[
        Status
        | DownloadProgress
        | SolveProgress
        | SolveScriptMessage
        | AskAnswer
        | TtsAudio
        | VoicePresets
        | SttLevel
        | SttPartial
        | SttFinal
        | QuizProgress
        | QuizItems
        | QuizGraded
        | WrongNotes
        | ReviewDue
        | ReviewGraded
        | DocProgress
        | DocImported
        | Docs
        | DrowsyCalibration
        | DrowsyStateMessage
        | CameraState
        | Error
    ]
):
    root: (
        Status
        | DownloadProgress
        | SolveProgress
        | SolveScriptMessage
        | AskAnswer
        | TtsAudio
        | VoicePresets
        | SttLevel
        | SttPartial
        | SttFinal
        | QuizProgress
        | QuizItems
        | QuizGraded
        | WrongNotes
        | ReviewDue
        | ReviewGraded
        | DocProgress
        | DocImported
        | Docs
        | DrowsyCalibration
        | DrowsyStateMessage
        | CameraState
        | Error
    )
