# GENERATED by packages/protocol/scripts/gen.mjs. Do not edit.

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, RootModel


class DirectorGodotMessages(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description='Transport: JavaScriptBridge. Coordinates are window CSS pixels, origin top-left.',
            title='Director <-> Godot messages',
        ),
    ]


class Vec(BaseModel):
    x: float
    y: float


class MoveTo(BaseModel):
    type: Literal['move_to']
    t: float | None = None
    x: float
    y: float
    speed: Annotated[
        float | None,
        Field(
            description='CSS px/s (default 85, about 2.4 steps/s; the walk reads best at <= ~120)',
            gt=0.0,
        ),
    ] = None


class SetPos(BaseModel):
    type: Literal['set_pos']
    x: float
    y: float


class Grab(BaseModel):
    type: Literal['grab']
    x: float
    y: float


class Release(BaseModel):
    type: Literal['release']


class Gesture(BaseModel):
    type: Literal['gesture']
    t: float | None = None
    name: Literal['write', 'point', 'nod', 'tap_desk', 'throw', 'idle']
    duration_ms: Annotated[float, Field(ge=0.0)]


class Emotion(BaseModel):
    type: Literal['emotion']
    t: float | None = None
    name: Literal['happy', 'surprised', 'sleepy', 'angry', 'neutral']
    weight: Annotated[float, Field(ge=0.0, le=1.0)]


class LookAt1(BaseModel):
    type: Literal['look_at']
    t: float | None = None
    x: float
    y: float
    target: Literal['user'] | None = None


class LookAt2(BaseModel):
    type: Literal['look_at']
    t: float | None = None
    x: float | None = None
    y: float | None = None
    target: Literal['user']


class IkTarget(BaseModel):
    type: Literal['ik_target']
    t: float | None = None
    x: float
    y: float


class Viseme(BaseModel):
    type: Literal['viseme']
    t: float | None = None
    aa: Annotated[float, Field(ge=0.0, le=1.0)]
    ih: Annotated[float, Field(ge=0.0, le=1.0)]
    ou: Annotated[float, Field(ge=0.0, le=1.0)]
    ee: Annotated[float, Field(ge=0.0, le=1.0)]
    oh: Annotated[float, Field(ge=0.0, le=1.0)]


class ThrowChalk(BaseModel):
    type: Literal['throw_chalk']
    t: float | None = None
    strength: Literal['soft', 'normal', 'hard']


class Ready(BaseModel):
    type: Literal['ready']


class Arrived(BaseModel):
    type: Literal['arrived']
    x: float
    y: float


class GestureDone(BaseModel):
    type: Literal['gesture_done']
    name: str


class HandPos(BaseModel):
    type: Literal['hand_pos']
    x: float
    y: float


class HitRect(BaseModel):
    type: Literal['hit_rect']
    x: float
    y: float
    w: Annotated[float, Field(ge=0.0)]
    h: Annotated[float, Field(ge=0.0)]


class ChalkImpact(BaseModel):
    type: Literal['chalk_impact']
    x: float
    y: float


class LoadAvatar(BaseModel):
    type: Literal['load_avatar']
    id: str
    path: Annotated[
        str | None,
        Field(
            description="Godot virtual FS path written via Engine.copyToFS, or res://. Omit with id 'default' to restore the built-in character."
        ),
    ] = None


class AvatarMeta(BaseModel):
    title: str
    version: str
    license_name: str
    license_url: str
    commercial_usage: str
    allow_redistribution: str
    modification: str
    credit_notation: str
    spec_version: str
    authors: list[str]


class AvatarLoaded(BaseModel):
    type: Literal['avatar_loaded']
    id: str
    meta: AvatarMeta


class AvatarError(BaseModel):
    type: Literal['avatar_error']
    id: str
    message: str


class GodotCommand(
    RootModel[
        MoveTo
        | SetPos
        | Grab
        | Release
        | Gesture
        | Emotion
        | IkTarget
        | Viseme
        | ThrowChalk
        | LoadAvatar
        | LookAt1
        | LookAt2
    ]
):
    root: (
        MoveTo
        | SetPos
        | Grab
        | Release
        | Gesture
        | Emotion
        | IkTarget
        | Viseme
        | ThrowChalk
        | LoadAvatar
        | LookAt1
        | LookAt2
    )


class GodotEvent(
    RootModel[
        Ready
        | Arrived
        | GestureDone
        | HandPos
        | HitRect
        | ChalkImpact
        | AvatarLoaded
        | AvatarError
    ]
):
    root: (
        Ready
        | Arrived
        | GestureDone
        | HandPos
        | HitRect
        | ChalkImpact
        | AvatarLoaded
        | AvatarError
    )
